# 2.6 Probability
## 2.6.1 Basic Probability Theory

In [14]:
%matplotlib inline
import torch
from torch.distributions import multinomial

fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 1., 0., 0., 0.])

In [18]:
counts = multinomial.Multinomial(10000, fair_probs).sample()
counts / 10000

tensor([0.1630, 0.1681, 0.1636, 0.1638, 0.1716, 0.1699])

In [24]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))
print(counts)
cum_counts = counts.cumsum(dim=0)
print(cum_counts)
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)
print(estimates)

tensor([[3., 3., 1., 3., 0., 0.],
        [0., 3., 2., 3., 1., 1.],
        [2., 1., 3., 1., 0., 3.],
        ...,
        [0., 0., 1., 1., 2., 6.],
        [2., 1., 4., 1., 1., 1.],
        [0., 0., 3., 2., 3., 2.]])
tensor([[  3.,   3.,   1.,   3.,   0.,   0.],
        [  3.,   6.,   3.,   6.,   1.,   1.],
        [  5.,   7.,   6.,   7.,   1.,   4.],
        ...,
        [837., 858., 809., 869., 761., 846.],
        [839., 859., 813., 870., 762., 847.],
        [839., 859., 816., 872., 765., 849.]])
tensor([[0.3000, 0.3000, 0.1000, 0.3000, 0.0000, 0.0000],
        [0.1500, 0.3000, 0.1500, 0.3000, 0.0500, 0.0500],
        [0.1667, 0.2333, 0.2000, 0.2333, 0.0333, 0.1333],
        ...,
        [0.1681, 0.1723, 0.1624, 0.1745, 0.1528, 0.1699],
        [0.1681, 0.1721, 0.1629, 0.1743, 0.1527, 0.1697],
        [0.1678, 0.1718, 0.1632, 0.1744, 0.1530, 0.1698]])
